---
output:
  md_document:
    variant: markdown_github
---

```{r setup, echo=FALSE}
iframe <- function(file, width = 800, height = 600)
  glue::glue('<iframe src="http://hosting.umons.ac.be/html/s807/sdd/sdd1_02/{file}" width="{width}" height="{height}" style="border:none;"></iframe>')
```

Exercice du cours de [Science des Données Biologiques I de l'Université de Mons, module 02](http://biodatascience-course.sciviews.org/sdd-umons/).

# Présentation de résultats statistique dans la littérature
## Guyliann Engels & Philippe Grosjean

## Objectif

- Réaliser des recherches sur internet afin de trouver des articles scientifiques sur une thématique libre. 
- Mettre en avant la méthode utilisée afin de présenter des analyses statistiques (dans le matériel et méthode, dans les résultats,...)

## Procédure

- Trouvez des articles scientifiques (2-3) dont la thématique vous intéresse (cela ne signifie pas que vous devez lire l'intégralité de l'article)
- Recherchez dans les articles la manière de présenter des analyses statistiques :
    + dans le matériel et méthode
    + dans les résultats
    + ...

Les résultats sont exprimé sous la forme d'un tableau ? d'un graphique ? dans le texte directement ? 

## Astuce

Un moteur de recherche performant afin de réaliser des recherches d'article est google scholar : <https://scholar.google.be>

## Rapport

- Rédigez une document de maximum 1 page exprimant les résultats de votre recherche dans la littérature
